---
kind: pipeline
type: docker
name: build-and-publish

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - main
  event:
    exclude:
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: build-and-publish
  pull: always
  image: cs3org/cs3apis:latest
  environment:
    SSH_KEY:
      from_secret: deploy_gh_key
  commands:
    # See https://github.com/drone/drone/issues/2692
    # write the ssh key to disk
    - mkdir /root/.ssh
    - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
    - shasum /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - stat /root/.ssh/id_rsa

    # add github to known hosts
    - touch /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/known_hosts
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
    - cs3apis-build -push-go -push-python -push-js -push-node -git-ssh # compile, build and publish all available languages

---
kind: pipeline
type: docker
name: build-only

platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: build-only
  pull: always
  image: cs3org/cs3apis:latest
  commands:
    - cs3apis-build # compile, build and publish all available languages
