---
name: Build only
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Build only
    runs-on: ubuntu-latest
    container: cs3org/cs3apis-build:master
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build-and-publish
        run: cs3apis-build
