---
name: Build and Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-publish:
    name: Buid and Publish CS3APIS
    runs-on: ubuntu-latest
    container: cs3org/cs3apis-build:master
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup-ssh
        env:
          SSH_KEY: ${{ secrets.ssh_key}}
        run: |
          mkdir /root/.ssh
          python3 -c "import os; file = open('/root/.ssh/id_rsa', 'w'); file.write(os.environ['SSH_KEY']); file.close()"
          shasum /root/.ssh/id_rsa
          chmod 400 /root/.ssh/id_rsa
          stat /root/.ssh/id_rsa
          touch /root/.ssh/known_hosts
          chmod 400 /root/.ssh/known_hosts
          ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
          cat /root/.ssh/id_rsa
      - name: build-and-publish
        run: cs3apis-build

