name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    name: Buid and Publish CS3APIS
    runs-on: ubuntu-latest
    container: cs3org/cs3apis-build:master
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build-and-publish
        run: cs3apis-build 
